# Generated by Django 5.2.7 on 2025-11-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="任务标题")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="任务描述"),
                ),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="是否完成"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="截止日期"
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("H", "High"), ("M", "Medium"), ("L", "Low")],
                        default="M",
                        max_length=1,
                        verbose_name="优先级",
                    ),
                ),
                (
                    "is_recurring",
                    models.BooleanField(default=False, verbose_name="是否为重复任务"),
                ),
                (
                    "ai_insight",
                    models.TextField(
                        blank=True,
                        help_text="基于用户历史记录生成的行为洞察文本",
                        null=True,
                        verbose_name="AI分析洞察",
                    ),
                ),
            ],
            options={
                "verbose_name": "任务",
                "verbose_name_plural": "任务",
                "ordering": ["due_date", "-created_at"],
            },
        ),
    ]
